spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.20.199:3306/midware
    username: remote
    password: issyu153
  activemq:
    broker-url: tcp://101.37.20.199:61616
#    pool:
#      max-connections: 10
#      use-anonymous-producers: true
#      enabled: true   #默认是false,即不使用连接池
    user: admin
    password: admin
#   close-timeout: 15s
#    pool:
#      use-anonymous-producers: true
  jms:
    pub-sub-domain: false  #true是topic false是queue
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 512MB   #上传文件大小设置

#debug: true

#需要解决queue和topic在同一个微服务无法同时使用的问题

#前后端跨域访问
server:
  port: 9000
